config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'trainings#index'
  resources :trainings, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :users, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boxing.rb
class Boxing < ActiveHash::Base
  self.data = [
    { id: 1, name: '実施内容' },
    { id: 2, name: '初級コンビネーション' },
    { id: 3, name: '上級コンビネーション' },
    { id: 4, name: '上級コンビネーション2' },
    { id: 5, name: '二の腕シェイプ集中コンビ' },
    # { id: 6, name: '二の腕コンビネーション2' }
  ]


  include ActiveHash::Associations
  has_many :trainings
end

app/models/training.rb
class Training < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :boxing
  belongs_to :user
  validates :boxing_id, numericality: { other_than: 1 , message: "必ず選んでください"}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :validatable, password_length: 8..128
         has_many :trainings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :new, :edit, :destroy]
  
  def index
    @training = Training.where(user_id: current_user.id)
  end

  def new
    @training = Training.new
  end

  def create
    @training = Training.new(training_params)
    if @training.save
      redirect_to root_path
    else
      flash[:notice] = "必ず選んでください"
      render :new
    end
  end

  def edit
     @training = Training.find(params[:id])
  end

  def update
    if training = Training.find(params[:id])
      training.update(training_params)
      redirect_to root_path
    else
      flash[:notice] = "必ず選んでください"
      render :edit
    end
  end

  def destroy
    training = Training.find(params[:id])
    training.destroy
    redirect_to action: :index
  end

  private

  def training_params
    params.require(:training).permit(:boxing_id).merge(user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @training = Training.all
    @name = current_user.name
    @trainings = current_user.trainings 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boxings/index.html.erb
<!-- #Sidebar# -->
<div class="d-flex flex-column flex-shrink-0 p-3 bg-light" style="width: 280px;">
  <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
    <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
    <span class="fs-4">Sidebar</span>
  </a>
  <hr>
  <ul class="nav nav-pills flex-column mb-auto">
    <li class="nav-item">
      <a href="#" class="nav-link active" aria-current="page">
        <svg class="bi me-2" width="16" height="16"><use xlink:href="#home"></use></svg>
        <%= link_to '記録する', new_boxing_path, method: :get %>
      </a>
    </li>
    <li>
      <a href="#" class="nav-link link-dark">
        <svg class="bi me-2" width="16" height="16"><use xlink:href="#speedometer2"></use></svg>
        Dashboard
      </a>
    </li>
    <li>
      <a href="#" class="nav-link link-dark">
        <svg class="bi me-2" width="16" height="16"><use xlink:href="#table"></use></svg>
        Orders
      </a>
    </li>
    <li>
      <a href="#" class="nav-link link-dark">
        <svg class="bi me-2" width="16" height="16"><use xlink:href="#grid"></use></svg>
        Products
      </a>
    </li>
    <li>
      <a href="#" class="nav-link link-dark">
        <svg class="bi me-2" width="16" height="16"><use xlink:href="#people-circle"></use></svg>
        Customers
      </a>
    </li>
  </ul>
  <hr>
  <div class="dropdown">
    <a href="#" class="d-flex align-items-center link-dark text-decoration-none dropdown-toggle" id="dropdownUser2" data-bs-toggle="dropdown" aria-expanded="false">
      <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2">
      <strong>mdo</strong>
    </a>
    <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser2">
      <li><a class="dropdown-item" href="#">New project...</a></li>
      <li><a class="dropdown-item" href="#">Settings</a></li>
      <li><a class="dropdown-item" href="#">Profile</a></li>
      <li><hr class="dropdown-divider"></li>
      <li><a class="dropdown-item" href="#">Sign out</a></li>
    </ul>
  </div>
</div>

<h1>トレマネ~便利な運動管理アプリ~</h1>
  <!-- <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "btn btn-danger"  %>
  <%= link_to 'ログイン', new_user_session_path, method: :get, class: "btn btn-danger"  %> -->

  <% if user_signed_in? %>
    <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "btn btn-danger"  %>
    <%= link_to current_user.name, "#", class: "user-nickname"  %>
  <% elsif %>
  <%= link_to 'ログイン', new_user_session_path, method: :get, class: "btn btn-danger"  %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>トレマネ-TrainingManagement-</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
      <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<%# 下部広告部分 %>
<div class='ad-footer-contents'>
  <p class='ad-footer-explain'>
    だれでもかんたん、人生を変えるフリマアプリ
  </p>
  <h2 class='ad-footer-title'>
    今すぐ無料ダウンロード！
  </h2>
  <div class='store-btn'>
    <%= link_to image_tag("app-store.svg", class:"apple-btn"), "#" %>
    <%= link_to image_tag("google-play.png", class:"google-btn"), "#" %>
  </div>
</div>
<%# /下部広告部分 %>

<div class='footer'>
  <div class='footer-contents'>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FURIMAについて</h2>
      <ul>
        <li><%= link_to '会社概要（運営会社)', "#", class: "footer-link" %></li>
        <li><%= link_to 'プライバシーポリシー', "#", class: "footer-link" %></li>
        <li><%= link_to 'FURIMA利用規約', "#", class: "footer-link" %></li>
        <li><%= link_to 'ポイントに関する特約', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FURIMAを見る</h2>
      <ul>
        <li><%= link_to 'カテゴリー一覧', "#", class: "footer-link" %></li>
        <li><%= link_to 'ブランド一覧', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FURIMAについて</h2>
      <ul>
        <li><%= link_to 'FURIMAガイド', "#", class: "footer-link" %></li>
        <li><%= link_to 'FURIMAロゴ利用ガイドライン', "#", class: "footer-link" %></li>
        <li><%= link_to 'お知らせ', "#", class: "footer-link" %></li>
      </ul>
    </div>
  </div>
  <%= link_to image_tag("furima-logo-white.png", class:"logo-white"), "#" %>
  <p>© FURIMA</p>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to image_tag("furima-logo-color.png", class:"furima-icon"), "/" %>
    <form class="search-form" action="#">
      <input class='input-box' placeholder='キーワードから探す'>
      <button class="search-button">
        <%= image_tag "search.png", class:"search-icon" %>
      </button>
    </form>
  </div>
  <div class='nav'>
    <ul class='lists-left'>
      <li><%= link_to 'カテゴリー', "#", class: "category-list" %></li>
      <li><%= link_to 'ブランド', "#", class: "brand-list" %></li>
    </ul>
    <% if user_signed_in? %>
      <ul class='lists-right'><li><%= link_to current_user.nickname, "#", class: "user-nickname"  %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout"  %></li>
        
      </ul>
    <% else %>
      <ul class='lists-right'>
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      </ul>
    <% end %>
    
  </div>
</header>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>
    <p class='second-fotter-text'>プライバシーポリシー</p>
    <p class='second-fotter-text'>FURIMA利用規約</p>
    <p class='second-fotter-text'>特定商取引に関する表記</p>
  </div>
  <%= image_tag "furima-logo-color.png", class:"second-fotter-logo"%>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("furima-logo-color.png", class:"second-logo"), "/" %>
</header>

app/views/shared/_sideber.html.erb
<div class="d-flex bg-denger">
  <!-- #Sidebar# -->
  <div class="d-flex  flex-column flex-shrink-0 p-3 bg-light" style="width: 280px; height: 100vh;  ">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 link-dark text-decoration-none">
      <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
      <%= image_tag("logo.png", class:"logo-icon me2", width: 70, height: 70) %><span class="fs-4">Menue</span>
    </a>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
      <li class="nav-item color rounded" >
        <%= link_to new_training_path, class: "nav-link ", "aria-current" => "page" do %>
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#home"></use></svg>
          <%= image_tag("boxing-icon.png", class: "icon me-2",  size: "24x24") %>
          記録する
        <% end %>
      </li>
      <li class="nav-item color rounded">
        <%= link_to new_training_path, class: "nav-link ", "aria-current" => "page" do %>
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#home"></use></svg>
          <%= image_tag("boxing-icon.png", class: "icon me-2",  size: "24x24") %>
          目標設定(工事中)
        <% end %>
      </li>
      <li class="nav-item color rounded">
        <%= link_to new_training_path, class: "nav-link  ", "aria-current" => "page" do %>
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#home"></use></svg>
          <%= image_tag("boxing-icon.png", class: "icon me-2",  size: "24x24") %>
          ユーザー設定(工事中)
        <% end %>
      </li>
      
      <%= month_calendar do |date| %>
  <%= date.day %>
<% end %>
      
      
    </ul>
    <hr>
    <% if user_signed_in? %>
    <div class="d-flex align-items-center ">
      <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "btn btn-danger me-2"  %>
      <%= link_to current_user.name, "#", class: ""  %>
    </div>
    <% elsif %>
    <div class="d-flex">
      <%= link_to 'ログイン', new_user_session_path, method: :get, class: "btn btn-danger me-2"  %>
      <%= link_to '新規登録', new_user_registration_path, method: :get, class: "btn btn-danger"  %>
    </div>
    <% end %>
  </div>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/trainings/edit.html.erb
<!-- <%= form_with(model: @model) do |form| %>
  <%= form.date_field :date, value: Date.current %>
  <%= form.submit %>
<% end %> -->
<%= render "shared/sideber" %>

<div class="new_main test ">
  <div class="boxing_form border p-3">
    <%= flash[:notice] %>
    <div class="p-3"></div>
      <%= form_with model: @training, url:training_path, local: true do |f| %>
      <div class="weight-bold-text">
        ボクシング(変更画面)
        <span class="indispensable">必須</span>
      </div>
      <%= f.collection_select(:boxing_id, Boxing.all, :id, :name, {}, {class:"select-box"}) %>
      <%= f.submit "変更する" ,class:"btn" %>
      <% end %>
      <%= button_to "削除する", training_path(@training), method: :delete, class:"btn" %>
    </div>
  </div>
</div>

app/views/trainings/index.html.erb
<%= render "shared/sideber" %>

<!-- メインページ -->

<div class="index-container" style="background-image: url('/assets/bg_nature.jpg');">
  <main class="bg-denger">
  <div class="test overflow-auto">

  
    <div class="main-logo">
      <h1><%= l Date.today, format: "%Y/%m/%d (%a)" %>の記録</h1>
      
    </div>
    <!-- <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "btn btn-danger"  %>
    <%= link_to 'ログイン', new_user_session_path, method: :get, class: "btn btn-danger"  %> -->

    <!-- 一覧表示 -->
    <div class="container test ">
      <div class="row">
        <% @training.reverse_each do |training| %>
          <div class="col-md-6">
            <%= link_to edit_training_path(training.id) do %>
              <div class="card p-3 mb-3">
                <figure class="p-3 mb-0">
                  <blockquote class="blockquote">
                    <p><%= training.boxing.name %></p>
                  </blockquote>
                  <figcaption class="blockquote-footer mb-0 text-muted">
                    <%= l training.created_at %>
                  </cite>
                  </figcaption>
                </figure>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <!-- !カレンダー -->
    <!-- <h1>カレンダー</h1>
    <%= month_calendar do |date| %>
  <%= date %>
<% end %> -->

 
  </div>
  </main>
</div>

app/views/trainings/new.html.erb
<%= render "shared/sideber" %>

<div class="new_main test ">
  <div class="boxing_form border p-3">
    <%= flash[:notice] %>
    <div class="p-3">
      <%= form_with model: @training, url: trainings_path, local: true do |f| %>
        <h1>ボクシングの記録</h1>
        <div class="form-group">
          <%= f.collection_select(:boxing_id, Boxing.all, :id, :name, {}, { class: "form-control select-box" }) %><span class="indispensable">必須</span>
        </div>
        <%= f.submit "投稿する", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>アカウントの編集</h2>
      <h5>トレマネアカウントの編集</h5>
      <%= link_to "ログアウト", "#", class: 'btn'%>
      <%= link_to "メインページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>